### ISSUE TITLE
Errors while first vagrant up

### ISSUE THREAD

**Issue by baliset2010** [bbc/nmos-joint-ri#9]
There were errors while 'vagrant up' at the first time.

```
    regquery:   Running setup.py bdist_wheel for cryptography: started
    regquery:   Running setup.py bdist_wheel for cryptography: finished with status 'error'
    regquery:   Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9a_ed7b1/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'),
__file__, 'exec'))" bdist_wheel -d /tmp/tmp2lf1ry2vpip-wheel- --python-tag cp35:
    regquery:   c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
    regquery:   compilation terminated.
    regquery:   Traceback (most recent call last):
    regquery:     File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
    regquery:       extra_postargs)
    regquery:     File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
    regquery:       spawn(cmd, dry_run=self.dry_run)
    regquery:     File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
    regquery:       _spawn_posix(cmd, search_path, dry_run=dry_run)
    regquery:     File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
    regquery:       % (cmd, exit_status))
    regquery:   distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    regquery:
    regquery:   During handling of the above exception, another exception occurred:
    regquery:
    regquery:   Traceback (most recent call last):
    regquery:     File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    regquery:       dist.run_commands()
    regquery:     File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    regquery:       self.run_command(cmd)
    regquery:     File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    regquery:       cmd_obj.run()
```

The same error occurred at node installation stage, too. So I've added 'libffi-dev' to apt install, in the provison_xxx.sh and re-create the image. Then I've got,...

```
    regquery: dpkg-source: info: building nmosreverseproxy using existing ./nmosreverseproxy_0.5.2.orig.tar.gz
    regquery: dpkg-source: info: building nmosreverseproxy in nmosreverseproxy_0.5.2-1.debian.tar.xz
    regquery: dpkg-source: info: building nmosreverseproxy in nmosreverseproxy_0.5.2-1.dsc
    regquery: dpkg-buildpackage: warning: using a gain-root-command while being root
    regquery: dpkg-buildpackage: source package nmosreverseproxy
    regquery: dpkg-buildpackage: source version 0.5.2-1
    regquery: dpkg-buildpackage: source distribution unstable
    regquery: dpkg-buildpackage: source changed by Simon Rankine <Simon.Rankine@bbc.co.uk>
    regquery:  dpkg-source --before-build nmosreverseproxy-0.5.2
    regquery: dpkg-checkbuilddeps: error: Unmet build dependencies: python3-all apache2-dev dh-systemd
    regquery: dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
    regquery: dpkg-buildpackage: warning: (Use -d flag to override.)
    regquery: Traceback (most recent call last):
    regquery:   File "setup.py", line 75, in <module>
    regquery:     long_description=long_description)
    regquery:   File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    regquery:     dist.run_commands()
    regquery:   File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    regquery:     self.run_command(cmd)
    regquery:   File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    regquery:     cmd_obj.run()
    regquery:   File "/usr/lib/python2.7/dist-packages/stdeb/command/sdist_dsc.py", line 140, in run
    regquery:     remove_expanded_source_dir=self.remove_expanded_source_dir,
    regquery:   File "/usr/lib/python2.7/dist-packages/stdeb/util.py", line 1397, in build_dsc
    regquery:     dpkg_genchanges(cwd=fullpath_repackaged_dirname)
    regquery:   File "/usr/lib/python2.7/dist-packages/stdeb/util.py", line 538, in dpkg_genchanges
    regquery:     process_command(args,cwd=cwd)
    regquery:   File "/usr/lib/python2.7/dist-packages/stdeb/util.py", line 183, in process_command
    regquery:     check_call(args, cwd=cwd)
    regquery:   File "/usr/lib/python2.7/dist-packages/stdeb/util.py", line 46, in check_call
    regquery:     raise CalledProcessError(retcode)
    regquery: stdeb.util.CalledProcessError: 3
    regquery: ERROR running: /usr/bin/python setup.py --command-packages stdeb.command sdist_dsc --dist-dir=/home/vagrant/nmos-reverse-proxy/deb_dist --use-premade-distfile=/home/vagrant/nmos-reverse-proxy/dist/nmosreverseproxy-0.5.2.tar.gz --with-python2=true --with-python3=true
    regquery: ERROR in deb_dist/tmp_py2dsc/nmosreverseproxy-0.5.2
    regquery: Makefile:68: recipe for target 'deb_dist' failed
    regquery: make: *** [deb_dist] Error 1
```

then, ...

```
    regquery: cp /home/vagrant/nmos-reverse-proxy/deb_dist/ips-reverseproxy-common_0.5.2-1*.deb /home/vagrant/nmos-reverse-proxy/dist
    regquery: cp /home/vagrant/nmos-reverse-proxy/deb_dist/python*nmosreverseproxy_0.5.2-1*.deb /home/vagrant/nmos-reverse-proxy/dist
    regquery: Selecting previously unselected package ips-reverseproxy-common.
    regquery: (Reading database ... 45503 files and directories currently installed.)
    regquery: Preparing to unpack .../ips-reverseproxy-common_0.5.2-1_all.deb ...
    regquery: Unpacking ips-reverseproxy-common (0.5.2-1) ...
    regquery: dpkg: dependency problems prevent configuration of ips-reverseproxy-common:
    regquery:  ips-reverseproxy-common depends on apache2; however:
    regquery:   Package apache2 is not installed.
    regquery:  ips-reverseproxy-common depends on apache2-bin (>= 2.4.18) | libapache2-mod-proxy-html; however:
    regquery:   Package apache2-bin is not installed.
    regquery:   Package libapache2-mod-proxy-html is not installed.
    regquery:  ips-reverseproxy-common depends on ssl-cert; however:
    regquery:   Package ssl-cert is not installed.
    regquery:  ips-reverseproxy-common depends on libxml2-dev; however:
    regquery:   Package libxml2-dev is not installed.
    regquery:
    regquery: dpkg: error processing package ips-reverseproxy-common (--install):
    regquery:  dependency problems - leaving unconfigured
    regquery: Errors were encountered while processing:
    regquery:  ips-reverseproxy-common
    regquery: Reading package lists...
```

and similar error happens for python-mdnsbridg, registryaggregator-build-deps, 

However, query/registration and mock node looks like working, by checking with a web browser.

Can I ignore these errors, or I'm missing some features?
